### ISSUE TITLE
Spike: Resumable multipart upload for large files

### ISSUE THREAD

**Issue by rmharrison** [CDCgov/data-exchange-csv#1]
### Requirements
- Upload large files. Think 10 GB+ [^1]
- Resumable
- Unique upload id (for uploader to check status, resume, cancel, etc.)

### Unilateral Tasks
- [x] Long-list of libraries that were considered
- [x] Short-list of libraries to assess
  * Our preferred development language is Kotlin, so Kotlin/Java multipart upload libraries are strongly prefered
- [x] Assess libraries
- [x] Presented short-listed libraries to team
- [x] Select lead candidate ==> 2022-11-07: Tus
- [x] Build API prototype with lead candidate
- [x] Present API prototype to team

### Tasks with dependencies on other teams 
- [ ] Talk to existing teams about how they did their uploaders
  - [ ]  IZDL portal > Upload a File
  - [ ] DCH Portal > Upload Files
  - [ ] ReportStream uploader. Somewhere in https://github.com/CDCgov/prime-reportstream. Max 10k records/submission ==> 50 MB single-file upload limit.

### Open questions
- Azure Functions have a [100MB max request size](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#azure-functions-limits). Can we use Azure functions with the multipart upload libraries?
  * For example, does each chunk of the multipart upload stay under the 100MB limit?

### Footnotes
[^1] Note the service limits for Azure Blob APIs...
Source accessed on 2022-09-15: https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob#remarks
![image.png](https://images.zenhubusercontent.com/62fe6e4e7c59c94524ab80ae/fe30a31d-76ed-44d5-b9cf-21d1c1c8a9cc)

**Comment by rmharrison** [comment]
Libraries long list
- https://tus.io/

Libraries short list

**Comment by rmharrison** [comment]
From @mkrystof 
> https://developers.google.com/drive/api/guides/manage-uploads#resumable
>
> I saw this the other day, it's the Google Drive API, which includes:
> - simple uploads
> - multipart uploads
> - **resumable uploads**
> 
> Seems like we could use this for inspiration.
