### ISSUE TITLE
Setup and test large file upload (10GB) with tusd service in azure container

### ISSUE THREAD

**Issue by mkrystof** [CDCgov/data-exchange-csv#23]
**Tasks**
- [x] Setup tusd
  * From public docker hub in Azure container
  * `OCIO-EDEDEV-C1` subscription
  * Link to Azure storage account `dataexchangedev` in container `bulkuploads`
  * Likely as an Azure App Service
- [x] Upload small sized file (~10 kB)
- [x] Upload medium sized file (~10 MB)
- [x] Upload large sized file (~10 GB / 9.31 GB) - **took 2 hr 36 min with 10Mbit upload connection**
- [x] Document steps to setup tusd as Azure App Service
- [x] Check-in Python client (tuspy, tus) code and add usage comments in the readme.

**Comment by mkrystof** [comment]
From https://learn.microsoft.com/en-us/azure/container-apps/compare-options

**Azure Container Apps**

Azure Container Apps enables you to build serverless microservices based on containers. Distinctive features of Container Apps include:
•	Optimized for running general purpose containers, especially for applications that span many microservices deployed in containers.
•	Powered by Kubernetes and open-source technologies like [Dapr](https://dapr.io/), [KEDA](https://keda.sh/), and [envoy](https://www.envoyproxy.io/).
•	Supports Kubernetes-style apps and microservices with features like [service discovery](https://learn.microsoft.com/en-us/azure/container-apps/connect-apps) and [traffic splitting](https://learn.microsoft.com/en-us/azure/container-apps/revisions).
•	Enables event-driven application architectures by supporting scale based on traffic and pulling from [event sources like queues](https://learn.microsoft.com/en-us/azure/container-apps/scale-app), including [scale to zero](https://learn.microsoft.com/en-us/azure/container-apps/scale-app).
•	Support of long running processes and can run [background tasks](https://learn.microsoft.com/en-us/azure/container-apps/background-processing).
Azure Container Apps doesn't provide direct access to the underlying Kubernetes APIs. If you require access to the Kubernetes APIs and control plane, you should use [Azure Kubernetes Service](https://learn.microsoft.com/en-us/azure/aks/intro-kubernetes). However, if you would like to build Kubernetes-style applications and don't require direct access to all the native Kubernetes APIs and cluster management, Container Apps provides a fully managed experience based on best-practices. For these reasons, many teams may prefer to start building container microservices with Azure Container Apps.
You can get started building your first container app [using the quickstarts](https://learn.microsoft.com/en-us/azure/container-apps/get-started).


**Azure App Service**
[Azure App Service](https://learn.microsoft.com/en-us/azure/app-service/) provides fully managed hosting for web applications including websites and web APIs. These web applications may be deployed using code or containers. Azure App Service is optimized for web applications. Azure App Service is integrated with other Azure services including Azure Container Apps or Azure Functions. When building web apps, Azure App Service is an ideal option.

**Azure Container Instances**
[Azure Container Instances (ACI)](https://learn.microsoft.com/en-us/azure/container-instances/) provides a single pod of Hyper-V isolated containers on demand. It can be thought of as a lower-level "building block" option compared to Container Apps. Concepts like scale, load balancing, and certificates are not provided with ACI containers. For example, to scale to five container instances, you create five distinct container instances. Azure Container Apps provide many application-specific concepts on top of containers, including certificates, revisions, scale, and environments. Users often interact with Azure Container Instances through other services. For example, Azure Kubernetes Service can layer orchestration and scale on top of ACI through [virtual nodes](https://learn.microsoft.com/en-us/azure/aks/virtual-nodes). If you need a less "opinionated" building block that doesn't align with the scenarios Azure Container Apps is optimizing for, Azure Container Instances is an ideal option.

**Comment by mkrystof** [comment]
**Setup steps to run tusd as an Azure App Service**

All steps will be done under the OCIO-EDEDEV-C1 subscription, which means you’ll need to use your CDC SU account for access.

1.	Create an App Service under the OCIO-EDEDEV-C1 subscription
  a.  Basics:
    - Subscription: OCIO-EDEDEV-C1 subscription
    - Resource group: ocio-ede-dev-moderate-hl7-rg
    - Name: as-bulk-upload-tusd
    - Publish: Docker Container
    - Operating System: Linux
    - Region: East US
    - Linux Plan: tf-hl7-app-service-plan (P2v2)
  
    b. Docker:
    - Options: Single Container
    - Image Source: Docker Hub
    - Access Type: Public
    - Image and tag: tusproject/tusd
    - Startup Command: -azure-blob-access-tier=hot -azure-object-prefix=tus-prefix -azure-storage=bulkuploads -azure-endpoint=https://dataexchangedev.blob.core.windows.net

    **Select [Review and Create]**

3. Modify the newly created App Service configuration (Settings -> Configuration).  Under Application Settings add the following “New application setting”:
    - AZURE_STORAGE_ACCOUNT: dataexchangedev
    - AZURE_STORAGE_KEY: <add the private key>
    - WEBSITES_PORT: 1080

    **Select [Save]**.  After you save these, it will restart the service automatically.

4.	Modify Settings-> Custom domains.  Turn HTTPS Only from the default ON to OFF.

5.	Select Overview and select the URL of the app service.  You should see something like:

```
Welcome to tusd
===============

Congratulations on setting up tusd! Thanks for joining our cause, you have taken
the first step towards making the future of resumable uploading a reality! We
hope you are as excited about this as we are!

While you did an awesome job on getting tusd running, this is just the welcome
message, so let's talk about the places that really matter:

- /files/ - send your tus uploads to this endpoint
- /metrics - gather statistics to keep tusd running smoothly
- https://github.com/tus/tusd/issues - report your bugs here

So quit lollygagging, send over your files and experience the future!

Version = v1.10.0
GitCommit = 19b1bccaa7fd0cee025f373d52c0535d017bea48
BuildDate = Mon Oct 10 19:00:28 UTC 2022
```

**Comment by mkrystof** [comment]
### Getting logs from app service from command line
Note you can also see live streaming logs from the Azure App Service in Azure portal under [app service] -> Monitoring -> Log stream

**Prepare the log (only need to do once)**
`az webapp log config --name as-bulk-upload-tusd --resource-group ocio-ede-dev-moderate-hl7-rg --docker-container-logging filesystem`

**Live stream the log tail**
`az webapp log tail --name as-bulk-upload-tusd --resource-group cio-ede-dev-moderate-hl7-rg`

**Comment by mkrystof** [comment]
Used https://testfiledownload.com/test-file-generator/ to generate the test files.
